### ISSUE TITLE
class方式存在问题，store下的属性无法获取

### ISSUE THREAD

**Issue by neoscript99** [nanjingboy/taro-mobx-sample#2]
# 定义
![image](https://user-images.githubusercontent.com/11485735/49213811-1720c100-f400-11e8-9a61-e91fc8252541.png)

# 运行时的store中没有用`@observable`定义的变量
![image](https://user-images.githubusercontent.com/11485735/49213883-49322300-f400-11e8-937b-1c5e663eb04f.png)

**Comment by nanjingboy** [comment]
目前`taro`不支持decorator作用在class property上

**Comment by nanjingboy** [comment]
@neoscript99  已经提过PR了，等待官方合并
