### ISSUE TITLE
请问下不支持dev:h5吗？编译报错

### ISSUE THREAD

**Issue by weizeng** [nanjingboy/taro-mobx-sample#3]
请问下不支持dev:h5吗？

> D:\leo\works\taro-mobx-sample>npm run dev:h5
> 
> > taro-mobx-sample@1.0.0 dev:h5 D:\leo\works\taro-mobx-sample
> > npm run build:h5 -- --watch
> 
> 
> > taro-mobx-sample@1.0.0 build:h5 D:\leo\works\taro-mobx-sample
> > taro build --type h5 "--watch"
> 
> 👽 Taro v1.2.7
> 
> 开始编译项目 taro-mobx-sample
> 创建  发现文件  src\app.js
> 创建  发现文件  src\app.scss
> 创建  发现文件  src\index.html
> 创建  发现文件  src\store\counter.js
> 创建  发现文件  src\pages\index\index.js
> 创建  发现文件  src\pages\index\index.scss
> 
> 
> ℹ️  Listening at http://127.0.0.1:10086/
> 
> 监听文件修改中...
> 
> 🙅   Failed to compile.
> 
> ./node_modules/@tarojs/mobx-h5/index.js
> Module not found: Can't resolve './Provider' in 'D:\leo\works\taro-mobx-sample\node_modules\@tarojs\mobx-h5'

**Comment by nanjingboy** [comment]
这个问题已经修了，要等官方发版本，https://github.com/NervJS/taro/issues/1943
